---
driver:
  name: docker
  use_sudo: false

# If you add new platforms below, include them in the .travis.yml file matrix
platforms:
- name: centos-6
- name: centos-7
- name: debian-7
  run_list: recipe[apt]
- name: debian-8
  run_list: recipe[apt]
- name: oraclelinux-6
  driver_config:
    platform: rhel
- name: ubuntu-15.10
  run_list: recipe[apt]
- name: ubuntu-16.04
  run_list: recipe[apt]

# Non-official images with systemd
- name: scientific-6.6
  driver_config:
    image: ringo/scientific:6.6
    platform: rhel
