rvm: 2.2

sudo: required

services: docker

env:
  matrix:
  - TESTS="style unit"
# Split up the test-kitchen run to avoid exceeding 50 minutes:
  - TESTS="integration[default-centos-6,verify]"
  - TESTS="integration[default-debian-7,verify]"
  - TESTS="integration[default-debian-8,verify]"
  - TESTS="integration[default-oraclelinux-6,verify]"
  - TESTS="integration[default-ubuntu-1510,verify]"
  - TESTS="integration[default-ubuntu-1604,verify]"
  - TESTS="integration[default-scientific-66,verify]"
  - TESTS="integration[ldap-debian-7,verify]"
  - TESTS="integration[ldap-debian-8,verify]"
  - TESTS="integration[ldap-ubuntu-1510,verify]"
  - TESTS="integration[ldap-ubuntu-1604,verify]"
  - TESTS="integration[attributes-centos-6,verify]"
  - TESTS="integration[attributes-debian-7,verify]"
  - TESTS="integration[attributes-debian-8,verify]"
  - TESTS="integration[attributes-oraclelinux-6,verify]"
  - TESTS="integration[attributes-ubuntu-1510,verify]"
  - TESTS="integration[attributes-ubuntu-1604,verify]"
  - TESTS="integration[attributes-scientific-66,verify]"

before_install:
- chef --version &> /dev/null || curl -L https://www.getchef.com/chef/install.sh | sudo bash -s -- -P chefdk -v 0.18.30
- eval "$(/opt/chefdk/bin/chef shell-init bash)"

install:
- chef exec bundle install --jobs=3 --retry=3 --without='doc integration_vagrant integration_cloud guard'

before_script:
# https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142455888
- sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
- chef --version
- cookstyle --version
- foodcritic --version

script: travis_retry chef exec bundle exec rake $TESTS
